apply from: 'gradle/scripts/helpers.gradle'

repositories {
    maven {
        name 'CurseMaven'
        url 'https://curse.cleanroommc.com'
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
    }
    mavenLocal()
}

dependencies {
    modCompileOnly 'curse.maven:the-twilight-forest-227639:3051450'
    modRuntimeOnly 'curse.maven:the-twilight-forest-227639:3051450'
}