apply from: 'gradle/scripts/helpers.gradle'

repositories {
    maven {
        name 'CurseMaven'
        url 'https://curse.cleanroommc.com'
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
    }
    mavenLocal()
    flatDir {
        dirs rootProject.file('libs')
    }
}

dependencies {
    compileOnly "com.cleanroommc:sponge-mixin:0.20.12+mixin.0.8.7"
    if (propertyBool('enable_lwjglx')) {
        compileOnly "com.cleanroommc:lwjglx:1.0.0"
    }

    modCompileOnly name: 'twilightforest-1.12.2-3.11.1021-universal'
    modRuntimeOnly name: 'twilightforest-1.12.2-3.11.1021-universal'

}