# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Shadow
enable_shadow = false

# Set this to true if you want to use old LWJGL2 methods.
# WARNING: Using LWJGL2 is recommended only for old-port compatibility.
enable_lwjglx = true

# Mod Information
mod_version = 1.0.0
root_package = com.zzhalex233
mod_id = twilightforestaddons
mod_name = Twilight Forest Addons

# Mixins
use_mixins = false
mixin_configs =
generate_mixins_json = false

# Mod Metadata
mod_description = An addon for The Twilight Forest that adds advanced magic maps, and an interactive large map GUI for boss structure teleportation.
mod_url =
mod_update_json =
mod_authors = zzhalex233
mod_credits =
mod_logo_path =

# Run Configurations
minecraft_username = Developer
extra_jvm_args =
enable_foundation_debug = false

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Access Transformers
use_access_transformer = true
access_transformer_locations = ${mod_id}_at.cfg

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
